"""Book 4 -- hi. Curation only; the rules live in tools/termlink/.

Curated on 2026-09-16 from THIS edition's own harvest -- never seeded from
book4_en.py and never from book3_hi.py. Every entry below was read off this
book's own corpus and checked against the English twin with the two collision
censuses (per-target frequency, per-target chapter set) before being kept.
Result: 3,014 links on 157 targets against English's 3,093 on 155; every
English target is reached and no target is linked in a chapter English does
not link it in.

What is Hindi-specific here, and what the measurements showed:

  * `lang_hi.py` sets WORD_TAIL to '' and DERIVE to False, so NOTHING is
    derived automatically: every oblique and plural a body actually writes has
    to be declared in DERIVED. Without that block this edition linked 2,676
    times where English links 3,093.

  * harvest.py accepts an \index{} entry from OUTSIDE a definition only when it
    contains a space ("if ' ' not in d or len(d) < 5: continue"). Hindi renders
    many of English's two-word terms as ONE hyphenated word -- stroke volume ->
    आघात-आयतन, cardiac output -> हृद्-निर्गम, hybrid zone -> संकर-क्षेत्र --
    and every one of them was silently dropped. That is what EXTRA is for here,
    and it is the single largest source of lost links in a Devanagari edition.

  * Three homographs that Hindi has and English does not (रूपांतरण, प्रेरण,
    अंडाशय) are in STOP, which leaves each term linked only in the chapter that
    pins its sense. Four more were repaired in the PROSE instead, because the
    word itself was the wrong choice there: प्रभावी (dominant) was being used
    for "effective" in ch. 14 and 19, भरती (recruitment) for "fill" in ch. 23,
    द्विगुणित (diploid) for "duplicated" in the ch. 11 solutions, and
    स्तंभ कोशिका (stem cell) for the palisade cell of ch. 15, now खंभ कोशिका.
    A fifth was a terminology split of my own: sarcomere was पेशीखंडिका in
    ch. 12 and सार्कोमियर in ch. 21, now सार्कोमियर everywhere.

What each key really does (verify per target, against the English twin):
  * DROP removes a term everywhere. It is the lever for a HOMOGRAPH -- a term
    whose translated surface is also an ordinary word.
  * STOP does NOT stop a homograph: the term falls through into the
    per-chapter map and keeps its links in every chapter that pins one sense.
    Sometimes that is exactly right (book3_en.py STOPs "substrate" for it).
  * EXTRA_PROTECT is the only lever against a form WORD_TAIL manufactures.
  * EXTRA values must be labels of THIS book (b2); audit them.

Regenerate after editing definitions or prose with:
  python3 tools/link_defined_terms.py --book 4 --lang hi --unwrap --apply
  python3 tools/link_defined_terms.py --book 4 --lang hi --apply

Terms are spelled as the bodies spell them: raw UTF-8, no TeX escapes.
"""

STOP = {
    # A homograph in HINDI that is not one in English. STOP (not DROP) is
    # right for all three: the term falls through to the per-chapter map and
    # keeps its links in the chapter that pins the sense.
    "रूपांतरण",   # bacterial TRANSFORMATION (ch. 3) and the ordinary
                  # "conversion": Pfr<->Pr (15), histone modification (12),
                  # the conversion of angiotensin (18), 4 more. 6 wrong links.
    "प्रेरण",     # embryonic INDUCTION (ch. 10) and the photoperiodic
                  # induction of flowering (ch. 14, 18 wrong links). English
                  # escapes this by accident: its \emph{Induction} is
                  # harvested CAPITALISED, so its pattern is "Induction" and
                  # the lower-case uses never match.
    "अंडाशय",     # the flower's OVARY (ch. 6) and the mammal's (ch. 8, 9) --
                  # the same word in Hindi. book4_en.py STOPs "ovary" for the
                  # same collision, and this is the exact counterpart.
}

DERIVED = {
    # Hindi obliques and plurals, read off THIS book's own corpus: lang_hi.py
    # sets WORD_TAIL = '' and DERIVE = False, so nothing is derived
    # automatically and every inflected form a body actually writes has to be
    # declared here. Generated by scanning the unwrapped corpus for
    # term + inflectional ending (ों / ाएँ / ाओं / ुओं / ियाँ / ियों / एँ / ें)
    # and then read one by one; derivational forms that are a DIFFERENT word
    # (धमनीय "arterial", पुष्पन "flowering", बीजाणु "spore", मकरंदी
    # "nectary") were rejected. Worth ~340 links.
    "केशिका": ("केशिकाएँ", "केशिकाओं",),   # केशिकाएँ 21, केशिकाओं 15
    "धमनिका": ("धमनिकाएँ", "धमनिकाओं",),   # धमनिकाओं 14, धमनिकाएँ 19
    "शिरा": ("शिराएँ", "शिराओं",),   # शिराएँ 12, शिराओं 14
    "स्तंभ कोशिका": ("स्तंभ कोशिकाएँ", "स्तंभ कोशिकाओं",),   # स्तंभ कोशिकाओं 7, स्तंभ कोशिकाएँ 10
    "बीज": ("बीजों",),   # बीजों 15
    "उत्परिवर्तन": ("उत्परिवर्तनों",),   # उत्परिवर्तनों 14
    "तंत्रिका-संधि": ("तंत्रिका-संधियाँ", "तंत्रिका-संधियों",),   # तंत्रिका-संधियाँ 12, तंत्रिका-संधियों 2
    "बीजांड": ("बीजांडों",),   # बीजांडों 13
    "निलय": ("निलयों",),   # निलयों 12
    "सार्कोमियर": ("सार्कोमियरों",),
    "मिट्टी का आहार-जाल": ("मिट्टी के आहार-जाल",),   # the one oblique the prose writes   # सार्कोमियरों 9
    "अलिंद": ("अलिंदों",),   # अलिंदों 8
    "लाइडिग कोशिका": ("लाइडिग कोशिकाएँ", "लाइडिग कोशिकाओं",),   # लाइडिग कोशिकाएँ 6, लाइडिग कोशिकाओं 2
    "भंडार": ("भंडारों",),   # भंडारों 6
    "संचयी उत्सर्जन": ("संचयी उत्सर्जनों",),   # संचयी उत्सर्जनों 6
    "हॉर्मोन": ("हॉर्मोनों",),   # हॉर्मोनों 6
    "अनुलेखन कारक": ("अनुलेखन कारकों",),   # अनुलेखन कारकों 5
    "न्यूरॉन": ("न्यूरॉनों",),   # न्यूरॉनों 5
    "पुटक": ("पुटकों",),   # पुटकों 5
    "पेशीतंतुक": ("पेशीतंतुकों",),   # पेशीतंतुकों 5
    "फ़र्न": ("फ़र्नों",),   # फ़र्नों 5
    "सर्टोली कोशिका": ("सर्टोली कोशिकाएँ", "सर्टोली कोशिकाओं",),   # सर्टोली कोशिकाएँ 3, सर्टोली कोशिकाओं 2
    "एककोशिकीय जीव": ("एककोशिकीय जीवों",),   # एककोशिकीय जीवों 4
    "जैवफ़िल्म": ("जैवफ़िल्में",),   # जैवफ़िल्में 4
    "द्रुमिका": ("द्रुमिकाएँ", "द्रुमिकाओं",),   # द्रुमिकाएँ 3, द्रुमिकाओं 1
    "पेशीकोरक": ("पेशीकोरकों",),   # पेशीकोरकों 4
    "प्रोटिस्ट": ("प्रोटिस्टों",),   # प्रोटिस्टों 4
    "मॉस": ("मॉसों",),   # मॉसों 4
    "रैमेट": ("रैमेटों",),   # रैमेटों 4
    "तंत्रिकाक्ष": ("तंत्रिकाक्षों",),   # तंत्रिकाक्षों 3
    "द्वार कोशिका": ("द्वार कोशिकाएँ", "द्वार कोशिकाओं",),   # द्वार कोशिकाओं 1, द्वार कोशिकाएँ 2
    "युग्मकोद्भिद": ("युग्मकोद्भिदों",),   # युग्मकोद्भिदों 3
    "विभज्योतक": ("विभज्योतकों",),   # विभज्योतकों 3
    "स्थायी अवस्था": ("स्थायी अवस्थाएँ",),   # स्थायी अवस्थाएँ 3
    "द्वितीय संदेशवाहक": ("द्वितीय संदेशवाहकों",),   # द्वितीय संदेशवाहकों 2
    "ध्रुवीय केंद्रक": ("ध्रुवीय केंद्रकों",),   # ध्रुवीय केंद्रकों 2
    "निवास-काल": ("निवास-कालों",),   # निवास-कालों 2
    "पुर्किंजे तंतु": ("पुर्किंजे तंतुओं",),   # पुर्किंजे तंतुओं 2
    "पेशीनलिका": ("पेशीनलिकाएँ", "पेशीनलिकाओं",),   # पेशीनलिकाएँ 1, पेशीनलिकाओं 1
    "युग्मविकल्पी बारंबारता": ("युग्मविकल्पी बारंबारताएँ",),   # युग्मविकल्पी बारंबारताएँ 2
    "विदलन": ("विदलनों",),   # विदलनों 2
    "शुक्रजनक नलिका": ("शुक्रजनक नलिकाएँ", "शुक्रजनक नलिकाओं",),   # शुक्रजनक नलिकाओं 1, शुक्रजनक नलिकाएँ 1
    "अंग-कलिका": ("अंग-कलिकाओं",),   # अंग-कलिकाओं 1
    "अनुकूलता": ("अनुकूलताओं",),   # अनुकूलताओं 1
    "अनुकूलन": ("अनुकूलनों",),   # अनुकूलनों 1
    "अनुक्रिया-मानक": ("अनुक्रिया-मानकों",),   # अनुक्रिया-मानकों 1
    "अपरा": ("अपराएँ",),   # अपराएँ 1
    "अभिवाह": ("अभिवाहों",),   # अभिवाहों 1
    "अर्धसूत्री विभाजन": ("अर्धसूत्री विभाजनों",),   # अर्धसूत्री विभाजनों 1
    "आक्रामक जाति": ("आक्रामक जातियाँ",),   # आक्रामक जातियाँ 1
    "क्लोन": ("क्लोनों",),   # क्लोनों 1
    "गुरुबीजाणु": ("गुरुबीजाणुओं",),   # गुरुबीजाणुओं 1
    "जीन-प्ररूप": ("जीन-प्ररूपों",),   # जीन-प्ररूपों 1
    "पराग कण": ("पराग कणों",),   # पराग कणों 1
    "पर्ण प्राथमिकांग": ("पर्ण प्राथमिकांगों",),   # पर्ण प्राथमिकांगों 1
    "पीढ़ी काल": ("पीढ़ी कालों",),   # पीढ़ी कालों 1
    "पीत प्रावस्था": ("पीत प्रावस्थाएँ",),   # पीत प्रावस्थाएँ 1
    "पुनर्संयोजन बारंबारता": ("पुनर्संयोजन बारंबारताएँ",),   # पुनर्संयोजन बारंबारताएँ 1
    "प्रेरण": ("प्रेरणों",),   # प्रेरणों 1
    "प्रोथैलस": ("प्रोथैलसों",),   # प्रोथैलसों 1
    "रैन्वियर की गाँठ": ("रैन्वियर की गाँठों",),   # रैन्वियर की गाँठों 1
    "लक्षण-प्ररूप": ("लक्षण-प्ररूपों",),   # लक्षण-प्ररूपों 1
    "लघुबीजाणु": ("लघुबीजाणुओं",),   # लघुबीजाणुओं 1
    "लिंग गुणसूत्र": ("लिंग गुणसूत्रों",),   # लिंग गुणसूत्रों 1
    "साम्य विभव": ("साम्य विभवों",),   # साम्य विभवों 1
    "सोरस": ("सोरसों",),   # सोरसों 1
    "स्टार्लिंग बल": ("स्टार्लिंग बलों",),   # स्टार्लिंग बलों 1
    "स्फुरण": ("स्फुरणों",),   # स्फुरणों 1
}

NO_CAPITAL = set()

EXTRA = {
    # A term the rules cannot reach, never a term they reach differently.
    # Every one of these is an English MULTI-WORD term that Hindi renders as a
    # single hyphenated word: harvest.py accepts an \index{} entry from
    # OUTSIDE a definition only when it contains a space (harvest.py, "if
    # ' ' not in d or len(d) < 5: continue"), so the Hindi rendering is
    # dropped where the English one is kept. Labels audited against the b2
    # label set; every one is defined in this book.
    "आघात-आयतन":   "prop:b2:heart:cycle",                  # stroke volume
    "हृद्-चक्र":    "prop:b2:heart:cycle",                  # cardiac cycle
    "हृद्-निर्गम":  "thm:b2:heart:starling",                # cardiac output
    "संकर-क्षेत्र": "prop:b2:speciation:reinforcement",     # hybrid zone
    "धूप-पत्ती":    "prop:b2:plant-plasticity:sunshade",    # sun leaf
    "छाँव-पत्ती":   "prop:b2:plant-plasticity:sunshade",    # shade leaf
    "छाया-परिहार":  "thm:b2:plant-plasticity:phytochrome",  # shade avoidance
    "द्विनिषेचन":   "prop:b2:angiosperm-reproduction:double",  # double fertilisation
    "जीन-प्रवाह":   "prop:b2:population-genetics:migration",   # gene flow
    "डिब्बा-प्रतिरूप": "thm:b2:biogeochemical-cycles:box",  # box model
    "प्रजनक-समीकरण": "thm:b2:population-genetics:heritability",  # breeder's equation
    "दाँव-बँटाई":   "thm:b2:plant-flowering:bet",           # bet hedging
    "पड़ोसी-जोड़":  "meth:b2:phylogenetic-trees:upgma",     # neighbour joining
    "मिट्टी-श्वसन": "prop:b2:living-soil:humus",            # soil respiration
    "सरकते-तंतु":   "prop:b2:muscle-movement:sliding",      # sliding filament
    "रसशिलापोषी":   "def:b2:microbial-metabolism:trophic",  # chemolithotroph
}

DROP = set()

# Never consume a `$` (see tools/termlink/protect.py).
EXTRA_PROTECT = [
    # "seed the clouds" -- the same collision book4_en.py protects, and the
    # same repair: बीज here is a verb-phrase object, not the seed of ch. 6.
    r"बादलों\s+के\s+बीज",
]

AMBIG_POLICY = "drop"
