"""Book 5 -- hi. Curation only; the rules live in tools/termlink/.

STUB. The edition agent fills this in from THIS edition's OWN harvest --
never by translating book5_en.py, and never by seeding from book4_hi.py.
A seeded EXTRA points at the other book's labels and ships as undefined
references; a seeded EXTRA_PROTECT masks the links you wanted. (You may read
book4_hi.py's PROSE NOTES for the language's homograph families -- that
knowledge does carry over -- but re-derive every key here.)

Procedure (translation_instruction.md section 5):

  1. Translate the bodies, then run the harvest and read the candidate list.
  2. Run BOTH homograph censuses against the English twin -- per-target
     frequency AND per-target chapter set. Neither is sufficient alone.
  3. Decide each flag by reading the link in context, never by the ratio.
  4. Regenerate:
       python3 tools/link_defined_terms.py --book 5 --lang hi --unwrap --apply
       python3 tools/link_defined_terms.py --book 5 --lang hi --apply
  5. Then a PLAIN dry run over the wrapped tree -- "links to insert" must be 0:
       python3 tools/link_defined_terms.py --book 5 --lang hi
     Anything else is a protect pattern that has stopped protecting (do not
     anchor a lookaround on a word that is itself a linked term).

English's own curation for this volume is a 28-word STOP list: Book 5 spans
twenty-seven fields, and one-word terms ("read", "domain", "fold", "seed",
"niche", "tolerance", "vector", "coat", "rod", "imprinting"...) change sense
between chapters, so STOP keeps each in its own chapter. Ask which of those
collisions survive translation and which new ones the target language mints
of its own -- the answer is different for every language.

Every key is optional: anything left out falls back to the defaults in
tools/link_defined_terms.py (empty sets, AMBIG_POLICY "drop").
"""

DERIVED = {
    # Hindi obliques and plurals, read off THIS edition's OWN corpus: lang_hi.py
    # sets WORD_TAIL = '' and DERIVE = False, so nothing is derived automatically
    # and every inflected form the Hindi body actually writes has to be declared.
    # Generated by scanning the unwrapped hi corpus for term + inflectional
    # ending (ों / ाएँ / ाओं / ुओं / ियाँ / ियों / एँ / ें / ें) and then read one
    # by one; derivational forms that are a DIFFERENT word (प्रतिरक्षा
    # "immunity" against प्रतिरक्षी "antibody", प्रांतस्था "cortex" against
    # प्रांत "domain", कर्कटजन "carcinogen", मधुमेही "a diabetic", पारजीन
    # "transgene", अवरोधक "inhibitor") were rejected.
    "प्रतिरक्षी": ("प्रतिरक्षियों",),
    "वाचन": ("वाचनों",),
    "मूल कोशिका": ("मूल कोशिकाएँ", "मूल कोशिकाओं"),
    "विक्षति": ("विक्षतियाँ", "विक्षतियों"),
    "कर्कट": ("कर्कटों",),
    "सूक्ष्मनलिका": ("सूक्ष्मनलिकाएँ", "सूक्ष्मनलिकाओं"),
    "विषाणु": ("विषाणुओं",),
    "प्रतिजैविक": ("प्रतिजैविकों",),
    "महाभक्षक": ("महाभक्षकों",),
    "अर्बुद": ("अर्बुदों",),
    "शलाका": ("शलाकाएँ", "शलाकाओं"),
    "संरेखण": ("संरेखणों",),
    "प्रतिजन": ("प्रतिजनों",),
    "रोम कोशिका": ("रोम कोशिकाएँ", "रोम कोशिकाओं"),
    "न्यूट्रोफिल": ("न्यूट्रोफिलों",),
    "विषाणुकण": ("विषाणुकणों",),
    "प्लाज़्मिड": ("प्लाज़्मिडों",),
    "न्यूक्लियोसोम": ("न्यूक्लियोसोमों",),
    "अंतःकाय": ("अंतःकायों",),
    "स्मृति कोशिका": ("स्मृति कोशिकाएँ", "स्मृति कोशिकाओं"),
    "लयनकाय": ("लयनकायों",),
    "प्लाज़्मा कोशिका": ("प्लाज़्मा कोशिकाएँ", "प्लाज़्मा कोशिकाओं"),
    "पूर्वगामी": ("पूर्वगामियों",),
    "गंडिका": ("गंडिकाएँ", "गंडिकाओं"),
    "हिस्टोन": ("हिस्टोनों",),
    "प्रारंभक": ("प्रारंभकों",),
    "द्विलड़ी विखंडन": ("द्विलड़ी विखंडनों",),
    "ऑर्थोलॉग": ("ऑर्थोलॉगों",),
    "हॉर्मोन": ("हॉर्मोनों",),
    "शीर्ष-कड़ी": ("शीर्ष-कड़ियाँ", "शीर्ष-कड़ियों"),
    "वृक्षाभ कोशिका": ("वृक्षाभ कोशिकाएँ", "वृक्षाभ कोशिकाओं"),
    "प्राकृतिक घातक कोशिका": ("प्राकृतिक घातक कोशिकाएँ", "प्राकृतिक घातक कोशिकाओं"),
    "पैरालॉग": ("पैरालॉगों",),
    "पक्ष्माभ": ("पक्ष्माभों",),
    "डेसिबल": ("डेसिबलों",),
    "ग्लोमेरुलस": ("ग्लोमेरुलसों",),
    "ग्राम-ऋणात्मक": ("ग्राम-ऋणात्मकों",),
    "ग्राम-धनात्मक": ("ग्राम-धनात्मकों",),
    "साइटोकाइन": ("साइटोकाइनों",),
    "सहजीविता": ("सहजीविताएँ", "सहजीविताओं"),
    "शंकु": ("शंकुओं",),
    "लसीका ग्रंथि": ("लसीका ग्रंथियों",),
    "पैनेथ कोशिका": ("पैनेथ कोशिकाएँ", "पैनेथ कोशिकाओं"),
    "गंडिका कोशिका": ("गंडिका कोशिकाएँ", "गंडिका कोशिकाओं"),
    "क्रांतिक सांद्रता": ("क्रांतिक सांद्रताएँ", "क्रांतिक सांद्रताओं"),
    "T कोशिका": ("T कोशिकाएँ",),
    "B कोशिका": ("B कोशिकाएँ",),
    "Hox जीन": ("Hox जीनों",),
    "स्थान कोशिका": ("स्थान कोशिकाओं",),
    "सिलेक्टिन": ("सिलेक्टिनों",),
    "लघु-शृंखला वसा अम्ल": ("लघु-शृंखला वसा अम्लों",),
    "प्रति-विषाणु औषध": ("प्रति-विषाणु औषधें", "प्रति-विषाणु औषधों"),
    "तारा-कोशिका": ("तारा-कोशिकाएँ", "तारा-कोशिकाओं"),
    "क्लोराइड कोशिका": ("क्लोराइड कोशिकाएँ", "क्लोराइड कोशिकाओं"),
    "कवकमूल": ("कवकमूलों",),
    "इंटिग्रिन": ("इंटिग्रिनों",),
    "इंटीग्रिन": ("इंटीग्रिनों",),
    "हॉलिडे संधि": ("हॉलिडे संधियाँ", "हॉलिडे संधियों"),
    "लसीकाणु": ("लसीकाणुओं",),
    "भ्रूणीय मूल कोशिका": ("भ्रूणीय मूल कोशिकाएँ",),
    "भ्रूणीय स्तंभ कोशिका": ("भ्रूणीय स्तंभ कोशिकाओं",),
    "पीड़ाग्राही": ("पीड़ाग्राहियों",),
    "निष्क्रियण": ("निष्क्रियणों",),
    "द्वार कोशिका": ("द्वार कोशिकाएँ", "द्वार कोशिकाओं"),
    "दिखने-की-बारंबारता वक्र": ("दिखने-की-बारंबारता वक्रों",),
    "जालक कोशिका": ("जालक कोशिकाएँ",),
    "चक्रिन": ("चक्रिनों",),
    "कोटर": ("कोटरों",),
    "कैस्पेज़": ("कैस्पेज़ों",),
    "आद्य-कर्कट जीन": ("आद्य-कर्कट जीनों",),
    "अंतर्न्यूरॉन": ("अंतर्न्यूरॉनों",),
    "AMPA ग्राही": ("AMPA ग्राहियों",),
    "स्वप्रेरक": ("स्वप्रेरकों",),
    "स्थिरपक्ष्माभ": ("स्थिरपक्ष्माभों",),
    "स्थानिक संरेखण": ("स्थानिक संरेखणों",),
    "सिग्मा कारक": ("सिग्मा कारकों",),
    "संग्रह नलिका": ("संग्रह नलिकाएँ",),
    "शिथिल घड़ी": ("शिथिल घड़ियाँ",),
    "लैंगरहैंस की द्वीपिका": ("लैंगरहैंस की द्वीपिकाएँ",),
    "लवण ग्रंथि": ("लवण ग्रंथियाँ",),
    "रोगजनक-संबद्ध आणविक नमूना": ("रोगजनक-संबद्ध आणविक नमूने",),
    "क्षति-संबद्ध आणविक नमूना": ("क्षति-संबद्ध आणविक नमूने",),
    "मैल्पीघी नलिका": ("मैल्पीघी नलिकाओं",),
    "मूल-ग्रंथिका": ("मूल-ग्रंथिकाओं",),
    "मध्यवर्ती तंतु": ("मध्यवर्ती तंतुओं",),
    "बेटमैन प्रवणता": ("बेटमैन प्रवणताएँ",),
    "बहिःस्राव पंप": ("बहिःस्राव पंपों",),
    "प्रोटिएज़ निरोधक": ("प्रोटिएज़ निरोधकों",),
    "पोषी हॉर्मोन": ("पोषी हॉर्मोनों",),
    "पूर्ण-जीनोम द्विगुणन": ("पूर्ण-जीनोम द्विगुणनों",),
    "पिरिमिडीन द्विलक": ("पिरिमिडीन द्विलकों",),
    "नॉड कारक": ("नॉड कारकों",),
    "नियोब्लास्ट": ("नियोब्लास्टों",),
    "द्वि-घटक तंत्र": ("द्वि-घटक तंत्रों",),
    "तारककाय": ("तारककायों",),
    "डाइडिऑक्सीन्यूक्लियोटाइड": ("डाइडिऑक्सीन्यूक्लियोटाइडों",),
    "जीर्ण कोशिका": ("जीर्ण कोशिकाएँ",),
    "घोषणात्मक स्मृति": ("घोषणात्मक स्मृतियाँ",),
    "कोशिका-चक्र": ("कोशिका-चक्रों",),
    "कैप्सिड": ("कैप्सिडों",),
    "केंद्री आसंजन": ("केंद्री आसंजनों",),
    "केंद्रकीय ग्राही": ("केंद्रकीय ग्राहियों",),
    "कुवलन रोग": ("कुवलन रोगों",),
    "किनारा प्रभाव": ("किनारा प्रभावों",),
    "ऐक्टिन तंतु": ("ऐक्टिन तंतुओं",),
    "आनुवंशिक रूपांतरित फ़सल": ("आनुवंशिक रूपांतरित फ़सलें",),
    "आक्रामक जाति": ("आक्रामक जातियाँ",),
    "अर्बुस्कुली कवकमूल": ("अर्बुस्कुली कवकमूलों",),
    "अंतःबीजाणु": ("अंतःबीजाणुओं",),
    "DNA विक्षति": ("DNA विक्षतियाँ",),
    "CpG द्वीप": ("CpG द्वीपों",),
    "AU-समृद्ध अवयव": ("AU-समृद्ध अवयवों",),
    "प्रचालनात्मक वर्गिकी इकाई": ("प्रचालनात्मक वर्गिकी इकाइयों",),
}

# Terms kept for their own chapter only (the harvest folds a STOPped term
# into the per-chapter local map).
STOP = {
    # Curated from THIS edition's own two censuses (per-target link frequency
    # and per-target chapter set) against the English twin, every flag then read
    # in context. Each of these is a Hindi word that carries a second sense in
    # another chapter, and each has an English counterpart in book5_en.py's own
    # STOP list -- the collision survived translation.
    # protein domain (structural biology) against Hox expression domains (23)
    # and antibody variable/constant domains (16)               [en: "domain"]
    "प्रांत",
    # protein fold (7) against "the folding clock" of glycoprotein sorting (8)
    #                                                             [en: "fold"]
    "वलन",
    # X-ray resolution (7) against sensory discrimination (17, 18), cell
    # differentiation (12, 24) and a resolvable difference (25)
    #                                                       [en: "resolution"]
    "विभेदन",
    # BLAST seed (6) against plant and prion seeds (7, 11, 20, 22) [en: "seed"]
    "बीज",
    # HMM profile (6) against a structural or expression profile  [en: "profile"]
    "प्रोफ़ाइल",
    # chromatin readers and writers (1) against the reader of a sequence and
    # the writer of a text (11)                        [en: "reader", "writer"]
    "पाठक", "लेखक",
    # bacterial transformation (12) against homeotic transformation (23),
    # memory consolidation (19), vitamin conversion (14) and the glucose
    # tolerance test's conversions (21)                            [no en twin:
    # English protects the homeotic collocations instead; रूपांतरण is wider]
    "रूपांतरण",
    # immunological tolerance (16) against glucose tolerance (21)
    #                                                        [en: "tolerance"]
    "सह्यता",
    # vesicle coat (8) against the bacterial and spore coat (12, 14) [en: "coat"]
    "आवरण",
    # innate barrier (15) against the blood--brain and other barriers (19, 20,
    # 24)                                                       [en: "barrier"]
    "अवरोध",
    # neural convergence and divergence (17) against sequence divergence (25)
    #                                      [en: "convergence", "divergence"]
    "अभिसरण", "अपसरण",
    # viral latency (13) against seed and bud dormancy (22)    [en: "latency"]
    "प्रसुप्ति",
    # microtubule catastrophe (9) against the error catastrophe of a
    # quasispecies (13)                                    [en: "catastrophe"]
    "विपर्यय",
}

# Terms removed from the term set entirely -- the lever for a true homograph,
# where STOP's per-chapter fall-through would still leave wrong links.
DROP = set()

# display -> label, for a target harvest.py cannot reach on its own (a welded
# or hyphenated compound, or a term whose head word is in NOT_A_TERM).
# AUDIT every entry against parts/bachelor-3/'s OWN label set before use.
EXTRA = {
    # Every one of these is a target ENGLISH reaches and Hindi lost, found with
    # a comm of the two target sets (English 188). Two causes, both structural:
    # (a) an English MULTI-WORD term that Hindi renders as a single HYPHENATED
    # word -- harvest.py accepts an \index{} from OUTSIDE a definition only when
    # it contains a space ("if ' ' not in d or len(d) < 5: continue"), so the
    # Hindi rendering is dropped where the English one is kept; (b) an OBLIQUE
    # form (का -> के) or a plural the body writes and the index does not.
    # Every label audited against parts/bachelor-3/'s own label set.
    "प्रतिजैविक-प्रतिरोध": "def:b3:bacteriology:resistance",       # antibiotic resistance
    "शोरबा-तनुकरण":        "met:b3:bacteriology:mic",              # broth dilution
    "चक्रिका-विसरण":       "met:b3:bacteriology:mic",              # disk diffusion
    "ब्रैग के नियम":       "met:b3:structural-biology:crystallography",  # Bragg's law, oblique
    "वलन-कीप":             "thm:b3:structural-biology:levinthal",  # folding funnel
    "कुंड-परिपक्वन":       "prop:b3:membrane-traffic:golgi",       # cisternal maturation
    "piRNA गुच्छों":       "def:b3:rna-regulation:pirna",          # piRNA clusters, oblique
    "ऊर्ध्वप्रवाही खुले वाचन-ढाँचे": "prop:b3:rna-regulation:translation",  # uORFs, oblique plural
    "क्षय-लंबाई":          "thm:b3:developmental-genetics:gradient",  # decay length
    "जीन-चालक":            "thm:b3:genetic-engineering:drive",     # gene drive
    "विषाणु-भार":          "thm:b3:virology:dynamics",             # viral load
    # Same hyphenated-compound cause, found by the FREQUENCY census rather than
    # the target census: the target was already reached by another display, but
    # English's commonest display for it was lost.
    "जीन-वृक्ष":    "prop:b3:molecular-evolution:ils",       # gene tree
    "जीन-वृक्षों":  "prop:b3:molecular-evolution:ils",
    "जाति-वृक्ष":   "prop:b3:molecular-evolution:ils",       # species tree
    "पाश-लाभ":      "thm:b3:endocrinology:loop",             # loop gain
}

# Regexes marking spans that must NOT be linked (a collocation where the term
# carries another sense). Never anchor one on a word that is itself a term.
EXTRA_PROTECT = [
    # "misreading" by the ribosome, not a sequencing read: the exact collision
    # book5_en.py avoids by STOPping "read", which Hindi does not need to STOP
    # because वाचन is only ever the noun (its chapter-14 and chapter-5 uses are
    # genuine sequencing reads and are linked).
    r'गलत\s+वाचन',
    # hormone conjugation (plant physiology), not bacterial conjugation --
    # the same span book5_en.py protects as "synthesis, conjugation".
    # Anchored on संश्लेषण/विनाश, neither of which is itself a linked term.
    r'संश्लेषण,\s+संयुग्मन',
]

# Displays that must not be matched in their capitalised form.
NO_CAPITAL = set()

# University register: an ambiguous term links nowhere rather than to a guess.
AMBIG_POLICY = "drop"
