"""Book 3 -- hi. Curation only; the rules live in tools/termlink/.

Curated on 2026-09-06 from THIS edition's own harvest -- never seeded from
book3_en.py and never from book2_hi.py. Every entry below was read off this
book's own corpus and checked against the English twin with the two collision
censuses (per-target frequency, per-target chapter set) before being kept.

What the measurements showed, and what is Hindi-specific:

  * `lang_hi.py` sets WORD_TAIL to '' and DERIVE to False, so NOTHING is
    derived automatically: every oblique/plural a body actually writes has to
    be declared in DERIVED. The block below was generated by scanning the
    corpus for term+ending forms that occur at least three times, then read
    one by one. Without it this edition linked 4,644 times where English
    links 5,495.

  * Most of book3_en.py's DROP list survives translation, because the same
    generic Hindi word carries the same second sense: ऊर्जा / पदार्थ /
    सूचना (the three exchanges), पर्यावरण, संबंध / जनन / पोषण (the three
    functions), दर, युग्मित, अम्ल, आधात्री, स्रोत, वाहक, पंप, कंकाल,
    प्रतिरोध, संघनन, स्थिरीकरण, अवशोषण, द्रवस्थैतिक, अनिश्चित, खंडीय,
    संतृप्त, विभेदन/विभेदित, लक्षण, स्पर्धी. Each was counted before being
    dropped; the census line that forced each one is noted below.

  * FOUR of English's drops do NOT collide in Hindi and are therefore kept,
    which is where this edition links where English cannot:
      - क्रियाधार is the enzyme substrate in all 69 places; the rock
        substrate of a succession is आधार in this edition (ch. 28), so
        English's STOP on "substrate" has no Hindi counterpart.
      - अभिज्ञान is molecular recognition in all 5 places; English drops
        "recognition" for the ordinary sense, which Hindi writes पहचान.
      - स्तरण is base stacking in all 5 places; the grana English collides
        with are ग्रैना here.
      - प्रचालक is the lac operator in all 18 places; a mathematical
        operator does not occur in this volume and would be संकारक.
    ध्रुवीय (polar) likewise keeps its 16 links: cell polarity is
    ध्रुवता and the verb is ध्रुवित, so the adjective is single-sense.

  * Collisions Hindi HAS and English does not, all caught by the chapter-set
    census and repaired in EXTRA_PROTECT rather than by dropping the term:
      - अंग is the organ AND the limb ("चार अंग", "पतले अंगों");
      - वंश is the genus AND a lineage ("स्तनधारी वंश", "पक्षी वंश");
      - अधिचर्म is the plant epidermis AND the skin's ("त्वचा का अधिचर्म");
      - चिकना is the smooth ER AND a smooth cartilage surface;
      - ध्रुवित is the polarised epithelial cell AND "to polarise a bond";
      - स्पर्धा is ecological competition AND competitive inhibition.
    Three further Hindi-only collisions were repaired in the PROSE instead,
    because the word itself was the wrong choice: परपोषी (heterotroph) was
    being used for the phage's HOST in ch. 6, 11 and 17 and is now पोषी;
    अंतर्वेशी/बहिर्वेशी (integral protein) were being used for
    intron/exon in the ch. 17 and 19 solutions and are now इंट्रॉन/एक्सॉन;
    and जड़ (root) was being used for "inert" in ch. 1, 10 and 17.

Regenerate after editing definitions or prose with:
  python3 tools/link_defined_terms.py --book 3 --lang hi --unwrap --apply
  python3 tools/link_defined_terms.py --book 3 --lang hi --apply

Terms are spelled as the bodies spell them: raw UTF-8, no TeX escapes.
"""

# NOT_A_TERM is left at its English default: its members are English
# result-words, none of which appears in a Hindi display in this book.

# STOP is deliberately EMPTY. It does not stop a homograph: harvest.py keeps a
# STOPped word out of the global `terms` table but still feeds it to the
# per-chapter `local` map, so any chapter with a single candidate definition
# links it anyway (measured by the Indonesian Book 3 agent: 38 surviving
# links). DROP is the one that removes a term from terms, local, nearest and
# primary alike.
STOP = set()

NO_CAPITAL = set()

EXTRA = {
    # Targets that carry links in English and none here, because the Hindi
    # display never coincides with a harvested definition title.
    # prop:b1:replication-mitosis:checkpoints -- 6 links in English, 0 here;
    # all 3 Hindi occurrences are the cell-cycle checkpoint (ch. 18).
    "जाँचबिंदु": "prop:b1:replication-mitosis:checkpoints",
    # prop:b1:mammal-organization:heatbudget -- 2 in English, 0 here; all 3
    # Hindi occurrences are the mammal's heat budget (ch. 2 and 9).
    "ऊष्मा-बजट": "prop:b1:mammal-organization:heatbudget",
    # def:b1:eukaryotic-cell:endomembrane -- the harvested key is the
    # two-word "गॉल्जी उपकरण"; the bare organelle name occurs 39 times and
    # linked nothing. All 39 were read: every one is the organelle, never
    # Camillo Golgi, who is not named in this volume. English carries the
    # same entry for the same reason.
    "गॉल्जी": "def:b1:eukaryotic-cell:endomembrane",
    # def:b1:cell-unit-of-life:prokeuk -- the harvested keys are the
    # two-word "सुकेंद्रकी कोशिका" / "प्राक्केंद्रकी कोशिका"; the bare nouns
    # carry the count (EN 54 links, HI 38 before these).
    "सुकेंद्रकी": "def:b1:cell-unit-of-life:prokeuk",
    "सुकेंद्रकियों": "def:b1:cell-unit-of-life:prokeuk",
    "प्राक्केंद्रकी": "def:b1:cell-unit-of-life:prokeuk",
    "प्राक्केंद्रकियों": "def:b1:cell-unit-of-life:prokeuk",
    # def:b1:eukaryotic-cell:plastid -- लवक is the harvested term and the
    # chloroplast is named inside its definition; the optional hyphenated
    # HEAD cannot reach a solid compound, so हरितलवक needs its own entry.
    "हरितलवक": "def:b1:eukaryotic-cell:plastid",
    "हरितलवकों": "def:b1:eukaryotic-cell:plastid",
    # def:b1:eukaryotic-cell:organelle -- the harvest registered a truncated
    # form; the word the bodies actually use is अंगक (EN 37 links, HI 20).
    "अंगक": "def:b1:eukaryotic-cell:organelle",
    "अंगकों": "def:b1:eukaryotic-cell:organelle",
    # def:b1:membranes-transport:osmosis -- EN 34, HI 15: the adjectives
    # carry the count and are single-sense here.
    "परासरणी": "def:b1:membranes-transport:osmosis",
    "अतिपरासरी": "def:b1:membranes-transport:osmosis",
    "अल्पपरासरी": "def:b1:membranes-transport:osmosis",
    "परासरणिता": "def:b1:membranes-transport:osmosis",
}

DROP = {
    # --- the three exchanges of the open system: 238 links in Hindi against
    # 0 in English, which drops "energy", "matter" and "information" for the
    # same reason. ऊर्जा alone reached 167 links across 25 chapters.
    "ऊर्जा", "पदार्थ", "सूचना",
    # पर्यावरण is the ordinary "environment" in 29 places
    "पर्यावरण",
    # --- the three functions of a mammal: 20 links in Hindi against 0 in
    # English ("relation", "reproduction", "nutrition")
    "संबंध", "जनन", "पोषण",
    # def:b1:enzymes:rate carried 36 Hindi links and 0 English ones: दर is
    # the growth rate, the death rate, the attack rate, the transpiration
    # rate. English drops "rate".
    "दर",
    # युग्मित is the coupled reaction AND "paired" (base pairing, sodium-
    # coupled symport): 24 places, mixed. English drops "coupling".
    "युग्मित",
    # def:b1:water-small-molecules:ph: EN 89, HI 181, of which अम्ल 97 --
    # almost all of them inside वसा अम्ल / ऐमीनो अम्ल / न्यूक्लिक अम्ल.
    "अम्ल",
    # def:b1:mammal-organization:compartments: EN 13, HI 64, of which
    # प्लाज़्मा 48 -- and about thirty of those are प्लाज़्मा झिल्ली, the
    # plasma MEMBRANE, in chapters 6, 9 and 10.
    "प्लाज़्मा",
    # आधात्री is the mitochondrial matrix (ch. 6) AND the extracellular
    # matrix of connective tissue and of the carbohydrate chapter (ch. 4, 10)
    "आधात्री",
    # def:b1:plant-transport:phloem: EN 24, HI 45. स्रोत is the ordinary
    # "source" in 26 places; ग्राही is the phloem sink in ch. 24 and the
    # RECEPTOR in ch. 7, 9, 14, 16 and 20 -- a collision English does not
    # have, since it writes "receptor".
    "स्रोत", "ग्राही",
    # def:b1:membranes-transport:transporters: EN 28, HI 109. वाहक is the
    # membrane carrier, the electron carrier and the oxygen carrier; पंप is
    # the proton pump and "no pump at all" (ch. 23, 24). English drops both.
    "वाहक", "पंप",
    # वाहिका is the xylem vessel AND the blood vessel (ch. 2, 4, 7, 22)
    "वाहिका", "वाहिकाओं", "वाहिकाएँ",
    # def:b1:cell-unit-of-life:resolution: EN 5, HI 17. विभेदन is the
    # microscope's resolution AND cell differentiation (ch. 3, 20, 28).
    "विभेदन", "विभेदित",
    # def:b1:classifying-biodiversity:characters: EN 28, HI 75, of which
    # लक्षण 49; outside ch. 29 every one is a symptom or a trait.
    "लक्षण",
    # def:b1:enzymes:inhibitors: EN 35, HI 60. स्पर्धी is the competitive
    # inhibitor in ch. 13 and the ecological COMPETITOR in ch. 26--28.
    "स्पर्धी",
    # def:b1:lipids:fattyacid gained chapters 12, 13, 21, 24, 26 and 27:
    # संतृप्त is the saturated chain AND a saturated enzyme, saturated
    # haemoglobin, saturated air, half-saturation.
    "संतृप्त",
    # def:b1:body-plans-tissues:segments: EN 19, HI 42. कंकाल is the
    # endoskeleton AND कार्बन-कंकाल, the carbon skeleton, which the optional
    # hyphenated HEAD of lang_hi.py swallows whole.
    "कंकाल",
    # ecological resistance (ch. 28) against "to resist" everywhere else
    "प्रतिरोध",
    # prop:b1:water-small-molecules:families: the condensation REACTION
    # against chromosome condensation (ch. 6, 17, 18)
    "संघनन",
    # def:b1:photosynthesis:fixation gained ch. 23 and 28: carbon fixation
    # against nitrogen fixation
    "स्थिरीकरण",
    # light absorption and absorbance against absorption in the gut
    "अवशोषण",
    # the hydrostatic skeleton against hydrostatic pressure (ch. 7, 24)
    "द्रवस्थैतिक",
    # prop:b1:flowering-plant-organization:modular: EN 3, HI 15. अनिश्चित is
    # indeterminate growth AND "अनिश्चित काल तक", indefinitely (ch. 5, 9,
    # 27, 29); खंडीय is modular growth AND ch. 1 and 20's ordinary sense.
    "अनिश्चित", "खंडीय",
    # विकृतीकरण is defined twice -- of DNA (ch. 11) and of protein (ch. 12) --
    # and the harvest keeps only the first, so half its links would be wrong.
    "विकृतीकरण",
}

# multi-word patterns use \s+ between words; never consume a `$`
EXTRA_PROTECT = [
    # NOTE ON DEVANAGARI IN THESE PATTERNS: a matra is its own code point, so
    # an optional Hindi ending must be written as a GROUP -- (?:ों)?, never
    # ों? -- exactly as book2_hi.py records.
    #
    # अंग is the organ (def:b1:mammal-organization:organ, 40 good links) and
    # also the LIMB: the cladogram's "four limbs" character and the mouse's
    # slender limbs.
    r'चार\s+अंग',
    r'पतले\s+अंगों',
    # वंश is the genus of the binomial and also a lineage
    r'स्तनधारी\s+वंश',
    r'पक्षी\s+वंश',
    # अधिचर्म is the plant epidermis (ch. 3, 23, 24) and the skin's (ch. 4)
    r'त्वचा\s+का\s+अधिचर्म',
    # चिकना is the smooth ER (ch. 6) and a smooth cartilage surface (ch. 4)
    r'चिकना,\s+संपीड्य',
    # ध्रुवित is the polarised epithelial cell (ch. 4) and "polarises the
    # bonds" of an enzyme's metal ion (ch. 13)
    r'बंधों\s+को\s+ध्रुवित',
    # स्पर्धा is ecological competition (23 good links) and, twice,
    # competitive inhibition: mannose competing for the carrier (ch. 7) and
    # the worked example on drugs (ch. 13)
    r'उसके\s+लिए\s+स्पर्धा\s+करती',
    r'औषधि\s+के\s+रूप\s+में\s+स्पर्धा',
    # पत्ती is the plant organ (255 good links) and, once, the cloverleaf
    # of a tRNA -- a shape, not an organ
    r'तिपतिया\s+पत्ती',
    # the cladogram's character "limb present or absent"
    r'अंग\s+उपस्थित',
]

DERIVED = {
    # Hindi obliques and plurals, read off THIS book's corpus: a form is
    # listed only where it occurs at least three times and only for a term
    # whose sense it keeps. Terms in DROP are absent by construction.
    "आंत्रकोशिका": ("आंत्रकोशिकाओं",),
    "आवास": ("आवासों",),
    "इंट्रॉन": ("इंट्रॉनों",),
    "उत्पादक": ("उत्पादकों",),
    "एंजाइम": ("एंजाइमों",),
    "एकशर्करा": ("एकशर्कराएँ",),
    "एक्सॉन": ("एक्सॉनों",),
    "ऊतक": ("ऊतकों",),
    "कूपिका": ("कूपिकाएँ", "कूपिकाओं"),
    "कोडॉन": ("कोडॉनों",),
    "कोशिका": ("कोशिकाएँ", "कोशिकाओं"),
    "क्रोमैटिड": ("क्रोमैटिडें", "क्रोमैटिडों"),
    "क्लोम": ("क्लोमों",),
    "गुणसूत्र": ("गुणसूत्रों",),
    "चैनल": ("चैनलों",),
    "जड़": ("जड़ें", "जड़ों"),
    "जीन": ("जीनों",),
    "जीव": ("जीवों",),
    "न्यूक्लियोटाइड": ("न्यूक्लियोटाइडों",),
    "न्यूक्लियोसोम": ("न्यूक्लियोसोमों",),
    "प्रोटीन": ("प्रोटीनों",),
    "फ़ॉस्फ़ोलिपिड": ("फ़ॉस्फ़ोलिपिडों",),
    "बफ़र": ("बफ़रों",),
    "बहुशर्करा": ("बहुशर्कराएँ", "बहुशर्कराओं"),
    "मूलरोम": ("मूलरोमों",),
    "राइबोसोम": ("राइबोसोमों",),
    "रसांकुर": ("रसांकुरों",),
    "लयनकाय": ("लयनकायों",),
    "लिपिड": ("लिपिडों",),
    "वर्गक": ("वर्गकों",),
    "वसा": ("वसाएँ", "वसाओं"),
    "विषाणु": ("विषाणुओं",),
    "शरीर-योजना": ("शरीर-योजनाएँ",),
    "संदमक": ("संदमकों",),
    "समुदाय": ("समुदायों",),
    "सम-रेखा": ("सम-रेखाएँ", "सम-रेखाओं"),
    "सहवाहक": ("सहवाहकों",),
    "सूत्रकणिका": ("सूत्रकणिकाएँ", "सूत्रकणिकाओं"),
    "हिस्टोन": ("हिस्टोनों",),
    "अंग": ("अंगों",),
    "अपघटक": ("अपघटकों",),
    "जाति": ("जातियाँ", "जातियों"),
    "पत्ती": ("पत्तियाँ", "पत्तियों"),
    "तना": ("तने", "तनों"),
    "ऐमीनो अम्ल": ("ऐमीनो अम्लों",),
    "आबादी": ("आबादियाँ", "आबादियों"),
    "क्षारक युग्म": ("क्षारक युग्मों",),
    "हाइड्रोजन बंध": ("हाइड्रोजन बंधों",),
    "विनिमय सतह": ("विनिमय सतहें",),
    "सूक्ष्म नलिका": ("सूक्ष्म नलिकाओं",),
    "पार्श्व शृंखला": ("पार्श्व शृंखलाएँ", "पार्श्व शृंखलाओं"),
    "द्वार कोशिका": ("द्वार कोशिकाएँ", "द्वार कोशिकाओं"),
    "ओकाज़ाकी खंड": ("ओकाज़ाकी खंडों",),
    "सक्रिय स्थल": ("सक्रिय स्थलों",),
    "ध्रुवीय अणु": ("ध्रुवीय अणुओं",),
    "अनुलेखन कारक": ("अनुलेखन कारकों",),
    "सेंट्रोमियर": ("सेंट्रोमियरों",),
    "वंश": ("वंशों",),
    "पर्णहरित": ("पर्णहरितों",),
    "परऑक्सीकाय": ("परऑक्सीकायों",),
    "निकेत": ("निकेतों",),
    "द्विशर्करा": ("द्विशर्कराएँ",),
    "डाइसल्फ़ाइड सेतु": ("डाइसल्फ़ाइड सेतुओं",),
    "जीनोम": ("जीनोमों",),
    "ग्लाइकोप्रोटीन": ("ग्लाइकोप्रोटीनों",),
    "क्रियाधार": ("क्रियाधारों",),
    "कैरोटिनॉइड": ("कैरोटिनॉइडों",),
    "ऑपेरॉन": ("ऑपेरॉनों",),
    "उपकला": ("उपकलाएँ", "उपकलाओं"),
    "आहार शृंखला": ("आहार शृंखलाएँ",),
    "अधिचर्म": ("अधिचर्मों",),
    # the harvest registered only the oblique of this one
    "कोशिकांगों": ("कोशिकांग",),
}

PRIMARY_OK = set()

AMBIG_POLICY = "drop"   # university book; matches book3_en.py
